apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: MONGO_URI
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
