backend:
  image:
    repository: ghcr.io/bashlogs/pipelines-backend
    tag: latest
  env:
    PORT: 5001
  service:
    port: 5001

frontend:
  image:
    repository: ghcr.io/bashlogs/pipelines-frontend
    tag: latest
  service:
    port: 80